# sub chart config
fullnameOverride: monitoring
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  #adminPassword: prom-operator
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        # SETME: service address of prometheus server
        url: http://monitoring-prometheus-server
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        # SETME: service address of prometheus server
        url: http://monitoring-loki:3100
        access: proxy
        isDefault: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: monitoring-dashboards
  #image:
  #  registry: mtr.devops.telekom.de
  #  repository: kubeprometheusstack/grafana
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik
      traefik.backend.loadbalancer.sticky: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    enabled: false
    hosts:
      - monitoring.example.com
    tls:
      - secretName: monitoring-example-com
        hosts:
          - monitoring.example.com
  persistence:
    inMemory:
      enabled: true
  testFramework:
    enabled: false
  rbac:
    namespaced: true
  initChownData:
    enabled: false
  grafana.ini:
    analytics:
      check_for_updates: false
    users:
      auto_assign_org_role: Viewer
    server:
      root_url: https://monitoring.example.com
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false
      org_role: Viewer
    auth.github:
      enabled: false
      #role_attribute_path: contains(groups[*], '@example/operator') &&  'GrafanaAdmin'

# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
prometheus:
  alertmanager:
    enabled: true
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-pushgateway:
    enabled: false
  releaseNamespace: false
  extraConfigmapMounts:
    - name: monitoring-scrapings
      mountPath: /etc/config
      subPath: ""
      configMap: monitoring-scrapings
      readOnly: true
  extraScrapeConfigs: |-
    - job_name: blackbox-http
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://monitoring.example.com
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: monitoring-prometheus-blackbox-exporter:9115
    - job_name: blackbox-http-icmp
      metrics_path: /probe
      params:
        module: [icmp]
      static_configs:
        - targets:
          - 1.1.1.1
          - 8.8.8.8
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: monitoring-prometheus-blackbox-exporter:9115
loki-stack:
  test_pod:
    enabled: false
  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://monitoring-loki:3100/loki/api/v1/push

# https://github.com/oauth2-proxy/manifests/blob/main/charts/oauth2-proxy/values.yaml
oauth2-proxy:
  enabled: true
  config:
    existingSecret: ""
    configFile: |-
      provider = "github"
      reverse_proxy = true
      upstreams = ["static://202"]
      cookie_domains = [".t.eumel.de"]
      whitelist_domains = [".t.eumel.de"]
      cookie_secure = true
      cookie_httponly = true
      cookie_samesite = "lax"
      set_xauthrequest = true
      pass_access_token = false
      skip_provider_button = true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - oauth.t.eumel.de
    path: /
    pathType: Prefix
    tls:
      - secretName: oauth2-proxy-tls
        hosts:
          - oauth.t.eumel.de
