{{- if index .Values "oauth2-proxy" "enabled" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "carbon-footprint.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-footprint.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "carbon-footprint.fullname" . }}-forward-auth@kubernetescrd,{{ .Release.Namespace }}-{{ include "carbon-footprint.fullname" . }}-oauth-errors@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: prometheus.t.eumel.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "carbon-footprint.fullname" . }}-prometheus-server
                port:
                  number: 80
  tls:
    - hosts:
        - prometheus.t.eumel.de
      secretName: prometheus-t-eumel-de
{{- end }}
